---
title: "Housing Data Analysis"
author: "Max Wang 1011602222, Divy"
date: "2025-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **1. Data and Background Research**

### **2. Overall Research Question**

```{r, echo=FALSE}
library(tidyverse)
HMI = read.csv("Housing Factors.csv")
OM = read.csv("Outstanding-Mortgages.csv")
AHI = read.csv("Avg-Household-Income-by-type.csv")

HMI = na.omit(HMI %>% filter(Year %in% c(2006:2016)))
d = left_join(HMI, OM, by="Year")
AHI = AHI %>% pivot_wider(id_cols = Year, names_from = Ownership, names_prefix = "Income_", values_from = Income)
d = left_join(d, AHI, by="Year")

d = d %>% mutate(housing_delta = No.of.constructions.started - Net.migration)

```

### **Graphs**

```{r, echo=FALSE}
ggplot(data = d, aes(x = Year)) + geom_point(aes(y = housing_delta), col="red") + 
  labs(title = "Housing Delta vs Year") + ylab("Housing Delta")

ggplot(data = d, aes(x = Year, y = Cumulative.Average.rent....)) + geom_point() +
  geom_line() +
  labs(title = "Cumulative Average Rent Prices vs Year") + 
  ylab("Cumulative Average Rent Prices")
```
