---
title: "STAA57 Group Project"
author: "Max Wang 1011602222"
date: "2025-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(tidyverse)
library(knitr)
HVS = read.csv("COVID-19_Hospitalizations_by_Vaccination_Status.csv")
zones = read.csv("COVID-19_Zones.csv")
outbreaks = read.csv("COVID-19_Outbreaks.csv")
cases = read.csv("2021_reported_COVID-19_Cases.csv")
```

## Overall Research Question:

## Tables

Average number of outbreaks for each zone type:

```{r, eacho=FALSE}
outbreaks_grouped = outbreaks %>% group_by(phu_name, date) %>% 
  summarize(numOutbreaks = sum(number_ongoing_outbreaks)) %>% 
  arrange(phu_name, date) %>% rename(Reporting_PHU=phu_name, start_date=date)
zones = zones %>% arrange(Reporting_PHU, start_date)
d = left_join(zones, outbreaks_grouped, by="start_date")
d2 = d %>% group_by(Status_PHU) %>% summarize(Outbreaks = mean(numOutbreaks)) %>%
  arrange(desc(Outbreaks))
kable(d2, "pipe")
```
